trigger:
  tags:
    include:
    - v?.*
pr: none


variables:
- group: codecov
- group: twine


resources:
  repositories:
  - repository: templates
    type: github
    name: aio-libs/azure-pipelines
    endpoint: aio-libs

stages:
- template: stage-lint.yml

- template: stage-test.yml
  parameters:
    pythonVersions:
      - '3.6'
      - '3.7'
      - '3.8'

- template: stage-deploy.yml
  parameters:
    pythonVersions:
      - '3.6'
      - '3.7'
      - '3.8'

- template: templates/stage-publish.yml@templates
  parameters:
    github: release-upload
