parameters:
  pythonVersions: []
  operatingSystems:
    - 'Linux'
    - 'Windows'
    - 'Mac'

stages:
- stage: build
  displayName: 'Build'

  jobs:
  - job: create distributions
    displayName: 'Tarball'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - template: templates/step-build.yml@templates
        parameters:
          steps:
            - script: |
                python setup.py sdist bdist_wheel
              displayName: 'Make tarball and universal wheel'

